# Generated by Django 4.0.3 on 2023-02-25 13:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_log', models.IntegerField()),
                ('network', models.CharField(max_length=32)),
                ('amount', models.IntegerField()),
                ('user_number', models.CharField(max_length=32)),
                ('sponsor_number', models.CharField(max_length=32)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('pay_url', models.CharField(default=uuid.uuid4, max_length=36)),
            ],
            options={
                'verbose_name_plural': 'incoming raw-data type custom',
                'ordering': ['timestamp'],
            },
        ),
    ]
