# Generated by Django 4.0.3 on 2023-02-22 19:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_log', models.IntegerField()),
                ('network', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('user_number', models.IntegerField()),
                ('sponsor_number', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('pay_url', models.CharField(default=uuid.uuid4, editable=False, max_length=36)),
            ],
            options={
                'verbose_name_plural': 'incoming raw-data type custom',
            },
        ),
        migrations.CreateModel(
            name='DataIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=255)),
                ('tag_value', models.CharField(max_length=255)),
                ('blob', models.CharField(max_length=800)),
                ('ip_incoming', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='FormalCellFind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(max_length=255)),
                ('phase', models.CharField(max_length=255)),
                ('jtype', models.IntegerField()),
                ('networkid', models.IntegerField()),
                ('jrequest', models.IntegerField()),
                ('jsessionid', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'incoming raw-data type 1',
            },
        ),
    ]
