# Generated by Django 4.0.3 on 2023-02-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=255)),
                ('tag_value', models.CharField(max_length=255)),
                ('blob', models.CharField(max_length=800)),
                ('ip_incoming', models.GenericIPAddressField()),
            ],
        ),
    ]
