# Generated by Django 4.0.3 on 2023-02-22 20:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codefunction',
            options={'ordering': ['timestamp'], 'verbose_name_plural': 'incoming raw-data type custom'},
        ),
        migrations.AlterField(
            model_name='codefunction',
            name='network',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='codefunction',
            name='pay_url',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
    ]
