# Generated by Django 4.0.3 on 2023-02-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormalCellFind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(max_length=255)),
                ('phase', models.CharField(max_length=255)),
                ('jtype', models.IntegerField()),
                ('networkid', models.IntegerField()),
                ('jrequest', models.IntegerField()),
            ],
        ),
    ]
