# Generated by Django 4.0.3 on 2023-02-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0002_formalcellfind'),
    ]

    operations = [
        migrations.AddField(
            model_name='formalcellfind',
            name='jsessionid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
