# Generated by Django 4.0.3 on 2023-02-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0003_formalcellfind_jsessionid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formalcellfind',
            options={'verbose_name_plural': 'incoming data raw expected type 1'},
        ),
        migrations.AddField(
            model_name='formalcellfind',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
