# Generated by Django 4.0.3 on 2023-02-20 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0004_alter_formalcellfind_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formalcellfind',
            options={'verbose_name_plural': 'incoming raw-data type 1'},
        ),
    ]
