# Generated by Django 4.0.3 on 2023-02-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0005_alter_formalcellfind_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_log', models.IntegerField()),
                ('network', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('user_number', models.IntegerField()),
                ('sponsor_number', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'incoming raw-data type custom',
            },
        ),
    ]
